#!/usr/bin/env bash

if ! [[ -d "./.docker_df" ]]
then
    mkdir "./.docker_df"
fi

docker system df -v > ./.docker_df/all_docker_df

line_containers=$(cat ./.docker_df/all_docker_df | grep -n "Containers space usage" | awk -F':' '{print $1}')
line_images=$(cat ./.docker_df/all_docker_df | grep -n "Images space usage" | awk -F':' '{print $1}')
line_volumes=$(cat ./.docker_df/all_docker_df | grep -n "Local Volumes space usage" | awk -F':' '{print $1}')
line_caches=$(cat ./.docker_df/all_docker_df | grep -n "Build cache usage" | awk -F':' '{print $1}')

cat ./.docker_df/all_docker_df | sed "$line_containers,$ d" | tail -n +$line_images > ./.docker_df/images_docker_df
cat ./.docker_df/all_docker_df | sed "$line_volumes,$ d" | tail -n +$line_containers > ./.docker_df/containers_docker_df
cat ./.docker_df/all_docker_df | sed "$line_caches,$ d" | tail -n +$line_volumes > ./.docker_df/volumes_docker_df
cat ./.docker_df/all_docker_df | tail -n +$line_caches > ./.docker_df/caches_docker_df

cat ./.docker_df/images_docker_df | sort -nk 10 > ./.docker_df/images_docker_df_sorted

