---
- name: find all files in ~/.dotfiles/scripts
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
  register: find_scripts

- name: remove dir for scripts
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: absent

- name: create dir for scripts
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: directory

- name: copy scripts
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.path | basename }}"
    path: "{{ ansible_env.HOME }}/scripts/{{ item.path | basename }}"
    state: hard
  with_items: "{{ find_scripts.files }}"
