---
- name: install packages for vim
  become: yes
  ansible.builtin.dnf:
    name:
      - nodejs
      - npm
      - python3-pip
    state: latest

- name: Install pip packages
  ansible.builtin.pip:
    name:
      - pylint
      - pynvim

- name: git clone vundle
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.config/nvim/bundle/Vundle.vim"


- name: instructions for further installation of vim
  ansible.builtin.debug:
    msg: "vim PluginInstall &&
      cd {{ansible_env.HOME }}/.config/nvim/bundle/coc.nvim &&
      sudo npm install -g yarn &&
      yarn install &&
      yarn build &&
      pip3 install jedi"

