#!/usr/bin/env bash


if ! [[ -d "./.clear_docker_logs" ]]
then
    mkdir "./.clear_docker_logs"
fi


function clear_volumes() {
    echo $(date) >> ./.clear_docker_logs/docker_volumes.log
    echo $(date) >> ./.clear_docker_logs/docker_volumes.err

    docker volume ls --filter dangling=true --filter name="^[a-f0-9]{64}$" | awk '{print $2}' | tail -n +2 | xargs -r docker volume rm \
        >> ./.clear_docker_logs/docker_volumes.log \
        2>> ./.clear_docker_logs/docker_volumes.err

    echo "" >> ./.clear_docker_logs/docker_volumes.log
    echo "" >> ./.clear_docker_logs/docker_volumes.err
}


function clear_images() {
    echo $(date) >> ./.clear_docker_logs/docker_images.log
    echo $(date) >> ./.clear_docker_logs/docker_images.err

    docker image ls --filter dangling=true | awk '{print $3}' | tail -n +2 | xargs -r docker rmi \
        >> ./.clear_docker_logs/docker_images.log \
        2>> ./.clear_docker_logs/docker_images.err

    echo "" >> ./.clear_docker_logs/docker_images.log
    echo "" >> ./.clear_docker_logs/docker_images.err
}


function clear_build() {
    echo $(date) >> ./.clear_docker_logs/docker_build.log
    echo $(date) >> ./.clear_docker_logs/docker_build.err

    echo "y" | docker builder prune \
        >> ./.clear_docker_logs/docker_build.log \
        2>> ./.clear_docker_logs/docker_build.err

    echo "" >> ./.clear_docker_logs/docker_build.log
    echo "" >> ./.clear_docker_logs/docker_build.err
}


case $1 in
    -v | --clear-volumes)
        clear_volumes
        ;;
    -i | --clear-images)
        clear_images
        ;;
    -b | --clear-build)
        clear_build
        ;;
    -a | --all)
        clear_volumes
        clear_images
        clear_build
        ;;
    -h | --help)
        echo "-v | --clear-volumes - clear dangling volumes"
        echo "-i | --clear-images - clear dangling images"
        echo "-b | --clear-build - clear dangling build"
        echo "-a | --all - clear all"
        ;;
    *)
        echo "error. Use: option -h"
        ;;
esac

